#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <taggir_icons.h>

int32_t taggir_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm taggir!");

    return 0;
}
