#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <taggir_icons.h>

#include "taggir.h"

int32_t taggir_app(void* p) {
    UNUSED(p);
    int out = SerialValidator("A4161222775113704");
    FURI_LOG_I("TAGGIR", "out is %d", out);

    return 0;
}
